name: Build  

on:
  workflow_call:
    inputs:
      conf:
        default: release
        required: false
        type: string
      os:
        required: true
        type: string
      artifacts:
        default: false
        required: false
        type: boolean

jobs:
  build:
    name: Build
    
    runs-on: ${{ inputs.os }}-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ammaraskar/msvc-problem-matcher@master
    - uses: ammaraskar/gcc-problem-matcher@master

    - name: Set preset name
      id: preset
      shell: bash
      run: |
        echo "name=${{ inputs.os }}-${{ inputs.arch }}-${{ inputs.conf }}" | sed s/ubuntu/linux/ >> $GITHUB_OUTPUT

    - name: Set up Windows compiler
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ inputs.arch }}

    - name: Configure
      run: cmake --preset ${{ steps.preset.outputs.name }}

    - name: Build
      run: cmake --build --preset ${{ steps.preset.outputs.name }}

    - name: Test
      run: ctest --timeout 5 --preset ${{ steps.preset.outputs.name }}
