name: Build  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
        conf: [release, debug]
        arch: [x64]
        exclude:
          - os: ubuntu
            arch: x86
          - os: macos
            arch: x86
    
    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: lukka/get-cmake@latest
    - uses: ammaraskar/msvc-problem-matcher@master
    - uses: ammaraskar/gcc-problem-matcher@master
    - uses: actions/checkout@v4
  
    - name: Set preset name
      id: preset
      shell: bash
      run: echo "name=${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.conf }}" | sed s/ubuntu/linux/ >> $GITHUB_OUTPUT

    - name: Set up Windows compiler
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11 

    - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
      uses: lukka/run-cmake@v10
      with:
        workflowPreset: ${{ steps.preset.outputs.name }}
