name: Integration  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Integration test
    
    runs-on: ubuntu-latest

    services:
      pushgateway:
        image: prom/pushgateway:latest
        ports: [9091]
      statsd:
        image: statsd/statsd-exporter:latest
        ports: [9125/udp, 9125/tcp]

    steps:
    - uses: actions/checkout@v4
    - run: cmake --preset linux-x64-debug
    - run: cmake --build --preset linux-x64-debug --target integration
    - run: out/build/linux-x64-debug/integration statsd_tcp ${{ job.services.statsd.ports[9125/tcp] }}
    - run: out/build/linux-x64-debug/integration statsd_udp ${{ job.services.statsd.ports[9125/udp] }}
    - run: out/build/linux-x64-debug/integration pushgateway ${{ job.services.pushgateway.ports[9091] }}
