name: Integration  

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Integration test
    
    runs-on: ubuntu-latest

    services:
      pushgateway:
        image: prom/pushgateway:latest
        ports: 
          - "9091:9091"
      statsd:
        image: prom/statsd-exporter:latest
        ports: 
          - "9125:9125/udp"
          - "9125:9125/tcp"

    steps:
    - uses: actions/checkout@v4
    - run: cmake --preset linux-x64-debug
    - run: cmake --build --preset linux-x64-debug --target integration
    - run: out/build/linux-x64-debug/integration statsd-tcp://localhost:9125
    - run: out/build/linux-x64-debug/integration statsd-udp://localhost:9125
    - run: out/build/linux-x64-debug/integration http://localhost:9091/metrics/job/test_job/instance/test_instance
