name: Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Integration test

    runs-on: ubuntu-latest

    services:
      pushgateway:
        image: prom/pushgateway:latest
        ports:
          - "9091:9091"
      statsd:
        image: prom/statsd-exporter:latest
        ports:
          - "9125:9125/udp"
          - "9125:9125/tcp"

    steps:
      - name: Export variables for vcpkg
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@v11
        with:
          runVcpkgInstall: true
        env:
          VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

      - run: cmake --preset linux-x64-debug
      - run: cmake --build --preset linux-x64-debug --target integration-test
      - run: out/build/linux-x64-debug/integration-test statsd+tcp://localhost:9125
      - run: out/build/linux-x64-debug/integration-test statsd+udp://localhost:9125
      - run: out/build/linux-x64-debug/integration-test pushgateway+http://localhost:9091/metrics/job/test_job/instance/test_instance
