name: "Mainline Checks"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
        conf: [release, debug, asan]
        arch: [x64]
        exclude:
        - os: ubuntu
          arch: x86
        - os: macos
          arch: x86
    uses:  ./.github/workflows/build.yml
    with:
      conf: ${{ matrix.conf }}
      os: ${{ matrix.os }}
      artifacts: true
