name: PVS-Studio
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-analyze:
    name: Analyze
    runs-on: ubuntu-latest
    if: contains(github.actor, 'dependabot') == false
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Install PVS-Studio
        run: |
          wget -q -O - https://files.pvs-studio.com/etc/pubkey.txt | sudo apt-key add -
          sudo wget -O /etc/apt/sources.list.d/viva64.list https://files.pvs-studio.com/etc/viva64.list
          sudo apt update
          sudo apt install pvs-studio

      - name: Ingest credentials
        run: pvs-studio-analyzer credentials ${{ secrets.PVS_STUDIO_CREDENTIALS }}

      - uses: lukka/get-cmake@latest # Set up latest cmake/Ninja
    
      - uses: lukka/run-vcpkg@v11 # Set up vcpkg and install dependencies
          with:
          runVcpkgInstall: true

      - name: Configure
        run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON --preset linux-x64-debug

      - name: Build
        run: cmake --build --preset linux-x64-debug --target metrics

      - name: Analyze
        run: pvs-studio-analyzer analyze -f out/build/linux-x64-debug/compile_commands.json 
                                         -e out/build/linux-x64-debug/_deps/ -e test/ -j

      - name: Convert report
        run: plog-converter -t sarif -o pvs-report.sarif PVS-Studio.log

      - uses: actions/upload-artifact@v4
        with:
          name: pvs-studio-log
          path: PVS-Studio.log
          retention-days: 1

      - uses: actions/upload-artifact@v4
        with:
          name: pvs-report-sarif
          path: pvs-report.sarif
          retention-days: 1

      - name: Publish report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: pvs-report.sarif
          category: PVS-Studio
